apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  source:
    repoURL: 'https://github.com/acenilsu/argocd-test.git' 
    targetRevision: HEAD  
    path: "k8s-manifests" 
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true