apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80  # Service portu
      targetPort: 8080
      nodePort: 30008
  type: NodePort  # Dışa açılabilmesi için LoadBalancer tipi
