name: CI

on:
  push:
    branches:
      - main
    tags:
      - 1.*
    paths:
      - "node-hello-world/**"
      - ".github/workflows/docker-image.yaml"
  workflow_dispatch: {} 

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "IMAGE_ID=${{ github.ref_name }}" >> $GITHUB_ENV
          else
              ts=$(date +%s)
              branch=${GITHUB_REF##*/}
              echo "IMAGE_ID=${branch}-${GITHUB_SHA::8}-${ts}" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish container image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: node-hello-world
          file: node-hello-world/Dockerfile
          tags: |
            snilsumelis/hello-world-for-argocd:${{ env.IMAGE_ID }}
