name: building docker image

on:
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}  

    - name: Build Docker image
      run: |
        docker build -t snilsumelis/hello-world-for-argocd:latest .
        
    - name: Push Docker image to Docker Hub
      run: |
        docker push snilsumelis/hello-world-for-argocd:latest
