
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '!k8s-manifests/**'
  workflow_dispatch: {}  # Manuel tetikleme için

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate image tag (short SHA)
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t snilsumelis/hello-world-for-argocd:${IMAGE_TAG} --push ./node-hello-world 

    - name: Optional - Print pushed image
      run: |
        echo "Pushed image: snilsumelis/hello-world-for-argocd:${IMAGE_TAG}"
