name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t snilsumelis/hello-world-for-argocd:${GITHUB_SHA} .
        docker push snilsumelis/hello-world-for-argocd:${GITHUB_SHA}
        docker tag snilsumelis/hello-world-for-argocd:${GITHUB_SHA} snilsumelis/hello-world-for-argocd:v1.x
        docker push snilsumelis/hello-world-for-argocd:v1.x
